### ISSUE TITLE
수행계획서 필요한 내용

### ISSUE THREAD

**Issue by JJoriping** [EThe0n/CPL-20181-Team4#1]
1. 과제 목적 및 필요성
1. 과제 내용 및 추진 방법
1. 과제 추진 일정 및 예산 활용 계획
1. 기대효과 및 활용방안
1. 예상되는 주요 과제성과

**Comment by JJoriping** [comment]
# 4. 기대효과 및 활용방안
  - 챗봇 서비스를 통해 언제 어디서나 신뢰도 높은 심리 검사 서비스를 제공
  - 낮은 수준의 심리 상담 서비스 제공
  - 메신저라는 플랫폼을 통하여 이용자들이 편안하게 사용할 수 있는 수준의 서비스 제공
  - 생활 심리 지능정보 서비스를 언제 어디서나 제공함으로써 일상에서 삶의 만족감 상승
  - 챗봇을 기반으로 심리 상담의 벽을 낮추는 효과

**Comment by JJoriping** [comment]
# 2. 과제 내용 및 추진 방법
- 자연어 처리 기술 숙지 및 인공지능 학습
  - 사용자와 챗봇 사이 교류는 자연어 텍스트로 이루어지므로 이에 대한 처리 기술을 연구
  - 인공지능이 보다 합리적인 판단을 할 수 있도록 다양한 자연어 샘플을 제공하여 인공지능을 학습
- 인공지능 채팅 시스템 구축
  - 사용자의 자연어 텍스트 입력을 인공지능으로 분석하고 적절한 대답을 사용자에게 자연어 텍스트로 출력
  - 인공지능이 사용자의 입력으로부터 해당 사용자의 심리 상태 및 감정 변화를 파악하고 이에 대한 보고서를 정기적으로 작성

**Comment by Ethe0n** [comment]
# 5. 예상되는 주요 과제성과

- 춘계에 열리는 한국정보처리학회나 한국정보과학회등에 논문 등록 및 포스터 발표.

- 소프트웨어 등록

**Comment by Ethe0n** [comment]
# 3. 과제 추진 일정 및 예산 활용 계획
[추진 일정]
![image](https://user-images.githubusercontent.com/14997644/37526398-8fde9850-2972-11e8-913a-6f4fc6f89d51.png)

[예산 활용 계획]
서버에 필요한 ODROID, 그리고 ODROID에 코드를 넣기 위해서 키보드 및 마우스가 필요함. (재료비 신청서 참고 후 그림 추가 필요.)
