### ISSUE TITLE
재료비에 필요한 링크 추가바람.

### ISSUE THREAD

**Issue by Ethe0n** [EThe0n/CPL-20181-Team4#2]
재료 신청서에 필요한 링크를 첨부해주기
각각 링크를 따로 다 올려줘야함
ex. 
키보드 : ~
마우스 : ~

**Comment by JangMinSeong** [comment]
키보드 : http://smartstore.naver.com/yurim/products/2514816021 

USB 허브 : http://smartstore.naver.com/yurim/products/2047150888

마우스 : http://smartstore.naver.com/yurim/products/379186681

**Comment by JJoriping** [comment]
* **ODROID-XU4**: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825
  * [옵션] 5V/4A Power Supply Asia/Korea Round Plug
* **ODROID-VU7 Plus**: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145981837236
* **VuShell for VU7**: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145154558544
* **32GB eMMC Module XU4 Linux**: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145628174287
   * [옵션] eMMC Module Reader Board for OS update
