### ISSUE TITLE
발표 초안에 내용이 필요함.

### ISSUE THREAD

**Issue by Ethe0n** [EThe0n/CPL-20181-Team4#4]
1. 첫장에 적힐 제목
2. 목차
3. 요약
 - 주제
 - 개발도구 등
4. 스터디
5. 교류
6. 논문
7. TODO

**Comment by Ethe0n** [comment]
4. 스터디
Node.JS, React.JS, PostgreSQL

**Comment by Ethe0n** [comment]
5. 교류 
오늘 정리하면 타대학측에 보낼거임
산업체 쪽에서 BDI, BAI, PHQ-15 등의 심리 검사표와 결과에 따른 조언(피드백)을 받음

**Comment by JangMinSeong** [comment]
3. 주제 변경사항 
회사측의 요구로 인해 개발범위에 변경이 생김
자연어 처리를 통한 열린봇을 개발 목표로 세웠으나 필요성이 없다는 판단으로 닫힌 봇을 목표로 변경
이를 통해 심리검사 플랫폼과 웹-앱 서버 시스템 구조 개선을 개발범위로 설정함

**Comment by Ethe0n** [comment]
7. TODO
자연어 처리기능을 탑재

**Comment by Ethe0n** [comment]
1. 제목
Mindle : 심리검사 플랫폼
으로?

**Comment by JangMinSeong** [comment]
6. 논문
3번의 주제 변경 사항으로 심리검사 플랫폼, 웹-앱 서버 시스템 구조를 개선하는 방법에 대해 2가지 논문을 작성할 계획

**Comment by JangMinSeong** [comment]
7. TODO 추가
앱으로 개발 (시작은 웹으로 작성)

**Comment by Ethe0n** [comment]
5. 교류 추가
팀원과의 교류 (회의 및 긴급회의)도 올리는게 좋을거 같다.

**Comment by JangMinSeong** [comment]
5. 교류 추가
TA와의 교류(재료비 신청한 상태라던가 논문에 필요한 이름 같은거?)

**Comment by Ethe0n** [comment]
3. 요약 - 개발도구
서버를 구동하기 위한 ODROID 사용.
