### ISSUE TITLE
논문 제출에 필요한 정보들을 정리해야함.

### ISSUE THREAD

**Issue by Ethe0n** [EThe0n/CPL-20181-Team4#5]
한국정보통신학회 제출 예정 : [http://kiice.org/](url)
요약문 양식 : [http://kiice.org/board.php?db=m6_3&uid=11&no=4392&c=view&page=1&sch_sel1=&sch_sel2=&sch_sel3=&sch_value=](url)
Abstract 작성시에 필요한 정보들이 있어야함.
1. 몇 편 낼건가
2. 주제 
3. 진행 방향

**Comment by JJoriping** [comment]
1. 전주에만 두 편을 내도 되는가요?
1. 만약 두 편을 낸다면
    1. Mindle - 온라인 심리 상담 및 치료를 위한 심리 상담 플랫폼
    1. 『Node.JS 기반의 고가용성 웹 어플리케이션 서버 시스템 구조 설계 및 구현』을 개선시킨 것
    - `i.`를 주력으로 삼고 여유가 있다면 `ii.`를 하는게 좋을 것 같습니다.
1. 개발 진행은 일단 아래와 같이 이루어질 것 같습니다. 개발 외 부분을 포함한 자세한 사항은 OPPM 등을 작성하는 것이 좋아 보입니다.
    1. 표준 정하기
    2. 표준을 따른 심리 상담 파일 작성하기
    2. 닫힌 봇 만들기
    3. 닫힌 봇이 심리 상담 파일을 읽어 질문하도록 하기
    4. 사용자의 응답을 분석하고 데이터베이스에 기록하기
    5. 사용자가 상담 결과를 확인할 수 있도록 하기

**Comment by Ethe0n** [comment]
1. 경험상 한 학회에 두편내는거 되는걸로 알고 있음
2. 그러면 일단 1을 중점으로 한다는 뜻은 2는 다른 학회에 내겠다는 말로 해석해도 되는가?
전주에 개최되는 학회에 요약본을 쓸 시간이 많지 않음.
